export const LLM_USER_AGENTS = [
  'ai2bot',
  'amazonbot',
  'anchor browser',
  'anthropic-ai',
  'applebot',
  'archive.org_bot',
  'bingbot',
  'bytespider',
  'ccbot',
  'chatgpt-user',
  'claude-searchbot',
  'claude-user',
  'claude-web',
  'claudebot',
  'cohere-ai',
  'deepseek',
  'diffbot',
  'duckassistbot',
  'google-cloudvertexbot',
  'google-extended',
  'gptbot',
  'meta-external',
  'mistralai-user',
  'novellum ai crawl',
  'oai-searchbot',
  'omgili',
  'perplexity-user',
  'perplexitybot',
  'petalbot',
  'proratainc',
  'timpibot',
  'webzio-extended',
  'youbot',
];
